language: ruby

rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.2.2"

gemfile:
  - "gemfiles/activerecord40.gemfile"
  - "gemfiles/activerecord41.gemfile"
  - "gemfiles/activerecord42.gemfile"

script: "bundle exec rake spec"
